version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "6000:5432"
    environment:
      POSTGRES_DB: soa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123